development:
  adapter: postgresql
  encoding: unicode
  database: discover_shows_development
  pool: 5
  # username: test_postgres
  # password:

test:
  adapter: postgresql
  encoding: unicode
  database: discover_shows_test
  pool: 5
  # username: test_postgres
  # password:

production:
  adapter: postgresql
  encoding: unicode
  database: discover_shows_production
  pool: 5
  # username: test_postgres
  # password:
