# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bb6a2281d095f23d558c0b3560ffb3e0db36876e535c79d25b4fce32a6720a3ee4886ded24da17c8559df52a8980938753103475cd3331970eb0581a512cb98

test:
  secret_key_base: 3bd99bba6f3c957af5d613e392d29cce725271a4d9ab4ee63dfb3a41ea29b8cd5b5a967c99be65f9ae898e99dc55f8b21b538551e9ecc2961acb1ddec2eae169

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
